### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by klainkaliber** [jkall/qgis-fit-plugin#2]
When importing a FIT-File I get the following Python error:

TypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType' 
Traceback (most recent call last):
  File "C:\Users/****/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-fit-plugin\fit.py", line 694, in opendialog
    self.import_fit()
  File "C:\Users/****/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-fit-plugin\fit.py", line 776, in import_fit
    self.fit2gpx_and_sqlite(infile)
  File "C:\Users/****/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-fit-plugin\fit.py", line 602, in fit2gpx_and_sqlite
    if not r_timestamp==None and r_timestamp>=session_start_time and r_timestampTypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'

File opens without issues in GPXSee.

**Comment by jkall** [comment]
Please try version 0.3 which includes a fix for:
> if not r_timestamp==None and r_timestamp>=session_start_time and r_timestampTypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'

**Comment by jkall** [comment]
closing due to lack of feedback
